services:
  recodarr:
    build: .
    image: recodarr:latest
    container_name: recodarr
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./data:/data
      - /srv/media:/srv/media
